name: weatherappflutterbloc
description: A new Flutter project.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.0
  bottom_drawer: ^0.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  motion_tab_bar_v2: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  
    # - assets/Images/c0.png
    - assets/Images/bg01.png
    - assets/Images/house.png
    - assets/Images/
    - assets/Images/container_back.png
    - assets/Images/moon_coud_fast.svg
    - assets/Images/moon.png
    - assets/Images/Sun_rain.png
    
