name: weatherappflutterbloc
description: A new Flutter project.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animated_notch_bottom_bar: ^1.0.0

  community_charts_flutter: ^1.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  
  glass_kit: ^2.0.1
  google_fonts: ^5.1.0
  gradient_line_graph: ^1.0.0
  motion_tab_bar_v2: ^0.2.6
  syncfusion_flutter_charts: ^22.2.8
  vs_scrollbar: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  
    # - assets/Images/c0.png
    - assets/Images/
    - assets/Images/bg01.png
    - assets/Images/fff.png
    - assets/Images/house.png
    - assets/Images/container_back.png
    - assets/Images/moon_coud_fast.svg
    - assets/Images/moon.png
    - assets/Images/Sun_rain.png
    - assets/Images/rain_weather.png
    - assets/Images/mooncloud.svg
    
